---
- name: "Adding role '{{ item_name }}'"
  debug: var=item_name

- set_fact:
    root_dir: "{{ playbook_dir }}/../roles/{{ item_name }}"

- name: "Delete previous data"
  file:
    dest:  "{{ item }}"
    state: absent
  with_items:
  - "{{ root_dir }}"
  - "{{ playbook_dir }}/{{ item_name }}.yml"

- name: "Create directories"
  file:
    dest:  "{{ item }}"
    state: directory
    owner: "root"
    group: "root"
    mode:  "u=rw,g=r,o=r"
  with_items:
  - "{{ root_dir }}"
  - "{{ root_dir }}/defaults"
  - "{{ root_dir }}/files"
  - "{{ root_dir }}/handlers"
  - "{{ root_dir }}/meta"
  - "{{ root_dir }}/tasks"
  - "{{ root_dir }}/templates"
  - "{{ root_dir }}/vars"

- name: "Deploy default main.yml files"
  template:
    src: "./main_{{ item }}.yml.j2"
    dest: "{{ root_dir }}/{{ item }}/main.yml"
    owner: "root"
    group: "root"
    mode: "u=rw,g=r,o=r"
  with_items:
  - tasks
  - vars
  - defaults
  - meta

- name: "Create gitkeeps"
  copy:
    content: ""
    dest: "{{ item }}/.gitkeep"
    owner: "root"
    group: "root"
    mode:  "u=rw,g=r,o=r"
  with_items:
  - "{{ root_dir }}/files"
  - "{{ root_dir }}/handlers"
  - "{{ root_dir }}/templates"

- name: "Deploy more defaults"
  template:
    src: "{{ item }}.j2"
    dest: "{{ root_dir }}/{{ item }}"
    owner: "root"
    group: "root"
    mode: "u=rw,g=r,o=r"
  with_items:
  - README.md
  - playbook.yml

- name: "Create link to playbook"
  file:
    src: "../roles/{{ item_name }}/playbook.yml"
    dest: "{{ playbook_dir }}/{{ item_name }}.yml"
    state: link
    owner: "root"
    group: "root"
    mode:  "u=rwx,g=rx,o=rx"
    force: yes

